pkg/devfile/parser/data/2.0.0/devfileJsonSchema200.go
pkg/util/util.go

* Remove "configuration"  as a required field in 2.0.0 devfile schema to workaround the downloaded devfile without configuration.
* Add  last "bool" parameter to client.Repositories.GetArchiveLink() to workaround different incompatible version of github.com/google/go-github used in odo

Workaround incompatible odo dep version and 2.0.0 devfile schema checks

---

main.go
pkg/devfile/parser/data/2.1.0/components.go
pkg/devfile/parser/data/2.1.0/components_test.go
pkg/devfile/parser/data/2.1.0/devfileJsonSchema210.go
pkg/devfile/parser/data/2.1.0/types.go
pkg/devfile/parser/data/versions.go
pkg/devfile/validate/validate.go

adds separate schema for devfile 2.1.0 that contains experimental dockerfile component feature and removes it from 2.0.0 schema
Known issues: currently all relevant components etc. are derived from common/types.go rather than the types.go file in the respective devfile version folder

Introduce 2.1.0/2.0.0 schema separation in devfile parser library

---

.gitignore

This PR add "parser" (the compiled binary) to .gitignore and remove "main" as it is the default binary built when "go build" is executed.

Git to ignore "parser" binary file

---

.github/workflows/go.yml
go.sum

added GitActions to do the following:
- get dependencies
- check build
- run tests
- check format
- check go mod status
Closes #11 and #17

Adding git actions

---

go.mod
go.sum
pkg/devfile/parser/data/2.0.0/components.go
pkg/devfile/parser/data/2.0.0/components_test.go
pkg/devfile/parser/data/2.0.0/types.go
pkg/devfile/parser/data/2.1.0/components.go
pkg/devfile/parser/data/2.1.0/components_test.go
pkg/devfile/parser/data/2.1.0/types.go
pkg/devfile/parser/data/common/types.go
pkg/devfile/parser/data/interface.go
pkg/devfile/validate/components.go
pkg/devfile/validate/components_test.go
pkg/testingutil/devfile.go

Updates the dependency on `devfile/api` to (at the time of writing) the current HEAD, picking up [changes](https://github.com/devfile/api/compare/1ae49a1fac4c..778718f72ad7d119be11eb2632b23cb5927be29e) in the devfile api -- notably:
- `devfile/api` has dropped the `v1alpha1` version in favor of `v1alpha2`
- A minor incompatibility in the project spec.
The two devfile/api PRs that impact this PR are
1. https://github.com/devfile/api/pull/120 - change representation of git project in devfile spec
2. https://github.com/devfile/api/pull/125 - switch to v1alpha2 version to allow breaking changes from v1alpha1
Related to https://github.com/devfile/parser/issues/26
I ran `make test` but am unfamiliar with the repo otherwise.

Update devfile/api dependency to pick up change to v1alpha2

---

pkg/devfile/parser/data/v2/commands.go

This PR adds back the `strings.tolower` to getcommands and updatecommand to unblock parser integration in odo
The removal would be fully done in https://github.com/devfile/library/pull/41
Tested with odo integration tests

add back strings.tolower to getcommands and updatecommand

---

tests/v2/devfiles/samples/testParent.yaml

Tests need to pull a parent/plugin using a uri so just merging the parent which the tests use. Can then add the uri to the tests before creating a pull request for the tests.

Upload parent in prep for schema tests

---

devfile.yaml
go.mod
go.sum
main.go
pkg/devfile/parser/data/v2/2.1.0/devfileJsonSchema210.go
pkg/devfile/parser/data/versions.go

The PR saves a copy of GA version of devfile 2.0 schema, and put latest devfile schema under 2.1.0 folder
This PR adds support for devfile 2.1, and pulls latest api pkg
modifies main.go to accept an arg which can be a http/https URL or a devfile path
Fixes https://github.com/devfile/api/issues/326
pass the unit tests and api tests

Support 2.0 and 2.1 schema

---

README.md

Adds code snippet and examples on how to parse a devfile and generate the Kube objects
Fixes https://github.com/devfile/library/issues/52
N/A

Provide code snippets in ReadMe

---

go.mod
go.sum
pkg/devfile/parser/context/context.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This PR adds relative URI support. 
`parseFromURI` checks the current devfile's abspath/url, and append to get the target uri and parse from that uri
https://github.com/devfile/api/issues/309
added unit test to test for relative uris

relative uri support

---

devfile.yaml
go.mod
go.sum
pkg/devfile/parse.go
pkg/devfile/validate/validate.go
tests/README.md
tests/api/parser_v200_verify_test.go
tests/utils/command_test_utils.go
tests/utils/component_test_utils.go
tests/utils/endpoint-test-utils.go
tests/utils/test_utils.go

This PR integrates validation into devfile/libaray
also updates the api test to generate valid devfiles for tests
https://github.com/devfile/api/issues/337

validation consolidation

---

go.mod
go.sum
pkg/devfile/parser/data/v2/common/options.go
pkg/devfile/validate/validate.go

This PR pulls in latest devfile/api with the fix for project/starterproject validation bug. 
Added back starterproject validation since the bug has been fixed
https://github.com/devfile/api/issues/337

add starterproject validation back

---

.github/workflows/go.yml
.gitignore
Makefile
README.md
go.mod
go.sum
main.go
replaceSchemaFile.go
updateApi.sh

automate the process to adopt the latest devfile/api pkg, and the latest schema
detail can be found in: https://github.com/devfile/api/issues/358
Fixes https://github.com/devfile/api/issues/358

Automatic update schema

---

pkg/devfile/parser/context/context.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This PR resolves the concurrency issue with URIMap. It removes the global URIMap defined in context.go, and save it in each devfileObj's cxt. 
Fixes https://github.com/devfile/api/issues/359
@mmulholla helped test with API tests, can run 20 consecutive runs without failure

concurrent URImap read and writes

---

go.mod
go.sum
tests/README.md
tests/v2/libraryTest/library_test.go
tests/v2/utils/library/project_test_utils.go
tests/v2/utils/library/test_utils.go

Adds tests for project and starter projects.
https://github.com/devfile/api/issues/331

add projects and starter projects to library tests

---

pkg/devfile/parser/context/apiVersion.go
pkg/devfile/parser/context/apiVersion_test.go

This PR improves error message of parser when it fail to parse due to no schema version is set. 
Displays devfile path/url to make it easier to debug
Fixes https://github.com/devfile/api/issues/327
updated unit tests

improve error message

---

README.md
pkg/devfile/parser/data/interface.go
pkg/devfile/parser/data/v2/commands.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/common/command_helper.go
pkg/devfile/parser/data/v2/common/command_helper_test.go
pkg/devfile/parser/data/v2/common/component_helper_test.go
pkg/devfile/parser/data/v2/common/options.go
pkg/devfile/parser/data/v2/common/project_helper.go
pkg/devfile/parser/data/v2/common/project_helper_test.go
pkg/devfile/parser/data/v2/components.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/projects.go
pkg/devfile/parser/data/v2/projects_test.go

Rather than having individual get funcs for different devfile objects like - `GetDevfileContainerComponents()`, `GetDevfileVolumeComponents()`, etc.; `GetComponents(common.DevfileOptions)` allows `DevfileOptions` to specify various options to filter: 
- commands
- command type - exec, composite, etc.
- command group kind - run, build, etc
- components
- component type - container, volume, etc
- projects 
- project source type - git, zip, etc
- starterProjects 
- project source type - git, zip, etc
Fixes https://github.com/devfile/api/issues/373
yes, new tests

Update Devfile Library Get Options

---

pkg/devfile/parser/context/content.go
pkg/devfile/parser/context/context.go
pkg/devfile/parser/parse_test.go
pkg/util/util.go

Supports parse from a path which contains `devfile.yaml` or `.devfile.yaml`
If the path/url does not ends with `.yaml`, than assumes the value is a directory, and will check for `devfile.yaml` or `.devfile.yaml` under that directory
`devfile.yaml` takes priority than `.devfile.yaml`
Fixes https://github.com/devfile/api/issues/61
manually tested

support .devfile.yaml and parse from a path

---

pkg/devfile/parser/data/interface.go
pkg/devfile/parser/data/v2/volumes.go
pkg/devfile/parser/data/v2/volumes_test.go

When reviewing PR https://github.com/openshift/odo/pull/4465, noticed that a same volume can be mounted at diff locations.  So it is not right to return the first mount path, we should return an array of all the mount paths for a specified container component
```
components:
- name: test2
volume:
size: 1Gi
- name: test
container:
image: xyz
volumeMounts:
- name: test2
path: /path1
- name: test2
path: /path2
- name: test3
container:
image: xyz
volumeMounts:
- name: test2
path: /path1
- name: test2
path: /path2
```
updated tests

Container can mount same vol at multiple places

---

pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This PR restricts the `registryURL` format, protocol is expected to be included as part of the `registryURL`
Since the filed is `registryURL`, it is expected to follow the url format. library does not need to help resolve the format, and should not take registry host as the url
Fixes https://github.com/devfile/api/issues/386
Update unit tests

restricts registryURL format

---

pkg/devfile/parser/context/context.go
pkg/devfile/parser/parse_test.go

Remove file name addition to URL, URL is expected to be a file path
Fixes https://github.com/devfile/api/issues/398
Updated unit test

remove file name addition to URL

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

This PR migrates the volume functions and logic that are devfile specific from the odo repo. Odo PR https://github.com/openshift/odo/pull/4627 refactored these code and this PR is a direct port of those functions
Part of https://github.com/devfile/api/issues/181
yes, ensured the tests were copied over too

Migrate devfile specific vol code from odo to devfile/library

---

pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils_test.go
pkg/devfile/parser/configurables_test.go
pkg/devfile/parser/data/interface.go
pkg/devfile/parser/data/v2/commands.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/common/command_helper_test.go
pkg/devfile/parser/data/v2/common/component_helper_test.go
pkg/devfile/parser/data/v2/common/options_test.go
pkg/devfile/parser/data/v2/common/project_helper_test.go
pkg/devfile/parser/data/v2/components.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/header_test.go
pkg/devfile/parser/data/v2/projects.go
pkg/devfile/parser/data/v2/projects_test.go
pkg/devfile/parser/parse_test.go
pkg/devfile/parser/sourceAttribute_test.go

return error in update apis (command, component, project, starter project) if the element requested to be updated does not exist.
event update does not fall into this rule
Fixes https://github.com/devfile/api/issues/448
added & updated unit test for the error cases

return error in update apis if the particular element does not exist

---

.gitignore
README.md
scripts/changelog-script.sh
scripts/updateApi.sh

- Provides a script to generate a changelog generator. Inspired by odo's [script](https://github.com/openshift/odo/blob/main/scripts/changelog-script.sh)
- Move the updateApi.sh to the scripts dir
N/A
Yes, made sure the changelog is generated properly and the devfile/api schemas are updating properly.

Add release changelog generator

---

go.mod
go.sum
pkg/devfile/parser/data/v2/2.1.0/devfileJsonSchema210.go
pkg/devfile/parser/sourceAttribute.go

imported the source attributes from devfile/api repo. 
Fixes https://github.com/devfile/api/issues/397

update source attribute to use the one imported from devfile/api

---

pkg/devfile/parser/data/v2/commands.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/components.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/events.go
pkg/devfile/parser/data/v2/events_test.go
pkg/devfile/parser/data/v2/projects.go
pkg/devfile/parser/data/v2/projects_test.go

This PR updates add apis to process everything before return an error. 
The error returned is a total error which contains error of all invalid elements during that add action
Fixes https://github.com/devfile/api/issues/449
update unit tests to check for error message

update add apis - process everything before return an error

---

go.mod
go.sum
pkg/devfile/generator/utils_test.go
pkg/devfile/parser/data/v2/2.1.0/devfileJsonSchema210.go
pkg/devfile/parser/data/v2/common/project_helper.go
pkg/devfile/parser/data/v2/common/project_helper_test.go
pkg/devfile/parser/parse_test.go

Pull in changes from devfile api before bumping up version to 2.2.0
so we can cut off and make a release for devfile 2.1.0 official release

library for devfile 2.1.0 cut off

---

.github/workflows/go.yml
.gitignore
Makefile
tests/README.md

Updated the go test command in the Makefile to include test coverage and report generation.   The go.yml was also updated to upload the test coverage report as a workflow artifact.   There was a minor fix where the originally command was missing the -v flag and so the details of the test cases (PASS/FAIL) were not being reported
https://github.com/devfile/api/issues/470
I ran the Makefile locally

enable test coverage + upload results in workflow

---

.github/workflows/go.yml
README.md
tests/README.md

This PR updates the ci to run test for pr against main branch

update the ci to run test for pr against main branch

---

pkg/util/util.go

Use of OS independent file path separator in KubeConfig exists util function
No issue
tests should pass as expected.

Use of OS independent file path separator in KubeConfig exists util function

---

go.mod
go.sum
tests/v2/libraryTest/library_test.go
tests/v2/utils/library/component_test_utils.go

Extends the automated tests to include testing for kubernetes and openshift components
https://github.com/devfile/api/issues/495
Yes, I ran the `make test` command locally and checked the test.log output to ensure there were no errors

Add kubernetes and openshift tests

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

This PR introduced a new function to get networking.k8s.io/v1 ingress, since v1beta1 ingress is no longer supported in future versions of k8s api
Fixes https://github.com/devfile/api/issues/504
Added new unit test

get networking v1 ingress

---

go.mod
go.sum
pkg/devfile/parser/context/content.go
pkg/devfile/parser/parse_test.go
pkg/devfile/parser/writer.go
pkg/devfile/parser/writer_test.go
pkg/util/util.go

This issue resolves a few small issues in library. 
it picks the latest API pkg with the fix for https://github.com/devfile/api/issues/500
it fixes a typo in util.go, `retrive` -> `retrieve`
it removes the `WriteJsonDevfile()` function, since we never officially support devfile.json, and no one is consuming that function now. so remove to avoid confusion.
Fixes https://github.com/devfile/api/issues/521
Fixes https://github.com/devfile/api/issues/520
Fixes https://github.com/devfile/api/issues/500
remove json writer test, and update the unit test name to be yaml writer.

resolve a few small issues

---

pkg/devfile/generator/utils.go

- attempting to create ingress without `PathType` specified
results in error
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>
[see title]
No i found this issue while attempting to move odo url creation to use networking v1 ingresses
Ingresses created by this should be apply on newer kubernetes cluster without error

Adding required field to networkingv1 ingress generator

---

go.mod
go.sum
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils_test.go
pkg/devfile/parser/configurables_test.go
pkg/devfile/parser/context/apiVersion_test.go
pkg/devfile/parser/context/context_test.go
pkg/devfile/parser/context/schema_test.go
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
pkg/devfile/parser/data/v2/attributes_test.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/common/command_helper_test.go
pkg/devfile/parser/data/v2/common/component_helper_test.go
pkg/devfile/parser/data/v2/common/options_test.go
pkg/devfile/parser/data/v2/common/project_helper_test.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/events_test.go
pkg/devfile/parser/data/v2/header_test.go
pkg/devfile/parser/data/v2/parent_test.go
pkg/devfile/parser/data/v2/projects_test.go
pkg/devfile/parser/data/v2/volumes_test.go
pkg/devfile/parser/data/v2/workspace_test.go
pkg/devfile/parser/parse_test.go
pkg/devfile/parser/sourceAttribute_test.go
pkg/devfile/parser/writer_test.go

This PR updates unit tests to check if error message matches the expected regexp
Fixes https://github.com/devfile/api/issues/523
Updated unit tests

update unit tests to check error messages

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

This PR filters out initContainers in `GetContainers()`
Fixes https://github.com/devfile/api/issues/532
>  **or**
call `GetContainers` against a devfile with init container, the output is expected to return all containers other than init containers

filter out init containers in GetContainers()

---

go.mod
go.sum
tests/v2/devfiles/samples/Parent.yaml
tests/v2/devfiles/samples/Test_Parent_KubeCRD.yaml
tests/v2/devfiles/samples/Test_Parent_LocalURI.yaml
tests/v2/devfiles/samples/Test_Parent_RegistryURL.yaml
tests/v2/libraryTest/library_test.go
tests/v2/utils/library/test_utils.go

* Introduces tests and test artifacts to validate parent devfiles
* Replaces the deprecated parseAndValidate method with ParseDevfileAndValidate 
https://github.com/devfile/api/issues/510
>  **or**
N/A These are just functional tests
N/A
N/A

parent tests

---

go.mod
go.sum
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go

this pr gets latest 2.2.0 schema
>  **or**

get latest 2.2.0 schema

---

go.mod
go.sum
pkg/devfile/generator/utils_test.go
pkg/devfile/parser/data/v2/common/command_helper_test.go
pkg/devfile/parser/parse_test.go
tests/v2/libraryTest/library_test.go

- Updates tests and utils to use boolean pointers
- Updates the parser tests to v2.1.0 and expands coverage to include all boolean fields
https://github.com/devfile/api/issues/545
>  **or**
- [X ] Unit/Functional tests
N/A
N/A
Client impact discussion in issue https://github.com/devfile/api/issues/545

update tests and utils to use boolean pointers

---

pkg/devfile/parser/data/v2/commands.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/components.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/projects_test.go

This PR updates the add functions to only append to list if the element does not exist in current list. 
Also updates unit tests to check for expected result.
Fixes https://github.com/devfile/api/issues/622
>  **or**

do not add to list if the element exist already

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go

This PR creates volume with emptyDir if `ephemeral=true`. Also updates unit test to test that specific case
Fixes https://github.com/devfile/api/issues/642
>  **or**

create volume with emptyDir if ephemeral is true

---

go.mod
go.sum
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go
pkg/testingutil/devfile.go

- Updates the parser to set defaults on nil boolean fields after workspace contents are merged.
- Updates the parser tests to include coverage for overriding unset/set values, and merging values for all boolean properties including the `RootRequired` field in the 2.2 spec. 
https://github.com/devfile/api/issues/615
>  **or**
- [ X] Unit/Functional tests …

Set default boolean values

---

go.mod
go.sum
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go

This PR pulls in latest devfile/api which includes the validation to resource requirement .
Fixes https://github.com/devfile/api/issues/672
>  **or**

pull latest devfile/api which includes resource requirement validation

---

go.mod
go.sum
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This PR compares the version of parent/plugin devfile with it's child devfile, and error out if greater than child devfile version. 
Fixes https://github.com/devfile/api/issues/686
>  **or**

error out if import devfile version is greater than child

---

go.mod
go.sum
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go
pkg/testingutil/devfile.go

pull latest devfile/api pkg and schema which contains the new field `autobuild` and `deploybydefault` for image components and kubernetes/openshift components, respectively. 
Fixes https://github.com/devfile/api/issues/693
>  **or**

new fields `autobuild` and `deploybydefault` for image components and kubernetes/openshift components

---

go.mod
go.sum
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go

use endpoint name as container port name and service port name if <= 15 chars. if > 15 chars (devfile spec before the change to shorten endpoint name limit), use `port-<portNumber>`
Fixes https://github.com/devfile/api/issues/700
>  **or**

use endpoint name as container port name and service port name

---

pkg/devfile/parser/data/v2/commands.go
pkg/devfile/parser/data/v2/commands_test.go
pkg/devfile/parser/data/v2/common/options.go
pkg/devfile/parser/data/v2/components.go
pkg/devfile/parser/data/v2/components_test.go
pkg/devfile/parser/data/v2/projects.go
pkg/devfile/parser/data/v2/projects_test.go

This PR adds a name filter for devfile object entries
fixes https://github.com/devfile/api/issues/750
>  **or**

add name filter

---

go.mod
pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go

Adds `Replicas` field to `DeploymentParams` struct. This will help initialize a Deployment with Replica set to what the tooling would like to have. By default, library doesn't set it to anything at the moment.
https://github.com/redhat-developer/odo/issues/5347
>  **or**

Add Replicas field to DeploymentParams struct

---

go.mod
pkg/testingutil/filesystem/default_fs.go
pkg/testingutil/filesystem/fake_fs.go
pkg/testingutil/filesystem/filesystem.go
pkg/testingutil/filesystem/singleton.go
pkg/testingutil/filesystem/watcher.go

This PR updates the filesystem pkg. 
>  **or**

update the filesystem

---

devfile.yaml
go.mod
go.sum
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

parse parent devfile with version reference
Fixes https://github.com/devfile/api/issues/765
>  **or**
Note: This change cannot be tested with production registry, as the server API change is still in staging.

parse parent devfile with version reference

---

CONTRIBUTING.md
README.md

This PR creates contributing.md file
moves some "maintainer-need-to-know" information from README to contributing.md
Fixes https://github.com/devfile/api/issues/808
>  **or**

create contributing.md file

---

pkg/devfile/parse.go
pkg/devfile/parse_test.go
pkg/devfile/parser/parse.go

This PR adds an `ExternalVariables` option to the `ParserArgs` structure, to be able to override variables defined in the devfile with other values when parsing a Devfile.
https://github.com/redhat-developer/odo/issues/5489
>  **or**

External variables can override Devfile variables

---

devfile.yaml
go.mod
go.sum
pkg/devfile/parse_test.go
pkg/devfile/parser/context/context.go
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
pkg/devfile/parser/devfileobj.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/writer.go
pkg/devfile/parser/writer_test.go
tests/v2/utils/library/test_utils.go

This PR converts kubernetest `uri` field to the `inlined` field with actual content in the `devfileObj` object in memory; so that the grobal variable defined can be substituted. An attribute `devfile.io/kubeComponent-originalURI` will be added to the kubernetes component as well. 
The PR also modified writer to check for the specific attribute and restore the uri back before write to the devfile; so that we are not modifying user's devfile content. 
fixes https://github.com/devfile/api/issues/906
>  - There is a separate …

906- variable substitution in kubernetes uri content

---

README.md
pkg/devfile/parser/parse.go
pkg/util/util.go
pkg/util/util_test.go

Adds proxy support for the util.GetHTTPRequest method and allows clients to specify a custom http timeout value
https://github.com/devfile/api/issues/926
>  **or**
Relying on console team to test
These changes are needed in order to fix a bug on the console.

proxy and custom timeout support

---

.codecov.yaml
.github/workflows/codecov.yml
.github/workflows/go.yml
Makefile

Signed-off-by: John Collier <jcollier@redhat.com>
Updates the code coverage reporting for this repository to use codecov.io
N/A

Update code coverage reporting

---

pkg/devfile/parser/reader.go
pkg/devfile/parser/reader_test.go

Updates the function's fs from internal to afero.
Why? Because 
- the internal fs belongs in the testing pkg `github.com/devfile/library/pkg/testingutil/filesystem`
- it makes sense to have a generic fs rather than an internal one for tools to adopt
N/A
Tests should pass

Change from internal fs to afero fs

---

pkg/devfile/parser/reader.go
pkg/devfile/parser/reader_test.go

Updated the method param to a nil, because a Filesystem is not required to be passed in if the src is URL or Data
N/A, but suggested in review here https://github.com/openshift/console/pull/12000#discussion_r985472126
>  **or**
Tests updated and should run successfully

Filesystem is not required when reading from URL and Data

---

README.md
pkg/devfile/parser/parse.go
pkg/util/util.go

Backports the changes to a dependency release supported by console 4.11.  Fix was verified in 4.12 by the console team
https://github.com/devfile/api/issues/926
>  **or**

backport proxy and custom timeout support to console v4.11

---

pkg/devfile/parser/parse_test.go
pkg/devfile/parser/reader.go
pkg/devfile/parser/reader_test.go
pkg/devfile/parser/utils.go
pkg/devfile/parser/utils_test.go

- Adds in util funcs to help get deploy components when reading the YAMLs for outerloop deploy, consolidated from https://github.com/openshift/console/blob/master/pkg/devfile/utils.go
- Updates test due to version change in https://github.com/devfile/registry/commit/49240fea7ae3ec83f4886a37b5dd651049424a72#diff-aaf25aac844fdfda61a801ed532a73148b946f390dca7eb30ed01718ee04b263
part of https://issues.redhat.com/browse/DEVHAS-192
>  - There is a separate tracking issue. Add the …

Add in util funcs to help get deploy components

---

pkg/devfile/parser/parse_test.go
pkg/devfile/parser/utils.go
pkg/devfile/parser/utils_test.go

Changes the util func param signature to take in Devfile data rather than Devfile object. Because we dont need DevfileObj.Ctx and is unnecessary export available in the function
N/A
>  **or**
Tests should pass

Change func param signature to avoid unneccessary Ctx

---

pkg/devfile/parser/context/content.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/reader.go
pkg/util/util.go

- Avoids collecting unintended telemetry where parent URLs and resources are called
- Updates the client identifier to `devfile-library` so we can distinguish these events better
https://github.com/devfile/api/issues/981
Will raise this in the community call/slack channel
Corresponding changes were made on the registry-support repo and deployed to a local cluster for testing.  Confirmed telemetry is not collected on parent references and intended events have the new client identifier `devfile-library`

telemetry updates

---

go.mod
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

Adds support for container-overrides attribute, as described in https://github.com/devfile/api/issues/920#issuecomment-1244059075.
The logic for this PR is motivated by https://github.com/devfile/devworkspace-operator/pull/967.
Fixes part of https://github.com/devfile/api/issues/936
>  **or**
Will work on docs once the PR is approved.
Override fields such …

Add support for container-overrides attribute

---

pkg/devfile/parser/reader.go

updates the reader ingress api. Since ODC/HAS are not using Ingresses yet, its better to use the latest api https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
N/A
>  **or**
tests should pass

Update ingress from extension to networking api

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

Adds support for pod-overrides attribute, as described in https://github.com/devfile/api/issues/920#issuecomment-1244059075.
The logic for this PR is motivated by https://github.com/devfile/devworkspace-operator/pull/967.
Fixes part of https://github.com/devfile/api/issues/936
>  **or**
Will work on docs once the PR is approved.
Override fields such as …

Add support for "pod-overrides" attribute

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

Signed-off-by: Parthvi Vala <pvala@redhat.com>
When `GetDeployment` is called for a Devfile schemaVersion less than 2.1.0. Currently it fails with error "top-level attributes is not supported in devfile schema version 2.0.0".
>  **or**
Use the following devfile for example:
<details>
<summary>devfile.yaml</summary>
```yaml
commands:
- exec:
commandLine: …
```

Fix GetDeployment function when Devfile SchemaVersion is less than 2.1.0

---

.github/workflows/go.yml

prevents latest gosec action from downloading
https://github.com/devfile/api/issues/1021
>  **or**

fix gosec action to 2.14 to prevent breakage

---

pkg/devfile/generator/utils.go
pkg/devfile/generator/utils_test.go

Signed-off-by: Parthvi Vala <pvala@redhat.com>
This PR fixes a faulty behavior when pod-overrides is defined at container level.
>  **or**
<details>
<summary>1. Use the following Devfile:</summary>
```yaml
commands:
- exec:
commandLine: npm install
component: runtime
group:
isDefault: true
kind: build
workingDir: ${PROJECT_SOURCE}
id: install
- exec: …
```

Fix pod-overrides for container level

---

pkg/devfile/parser/parse.go

Removes the excessive error wrapping
For example, this is what we see in HAS:
```
Status:
Conditions:
Last Transition Time:  2023-02-16T21:49:29Z
Message:               Component create failed: failed to parse kubernetes/openshift component from uri to inlined: failed to convert Kubernetes Uri to inlined for component 'kubernetes-only-deploy': error getting kubernetes resources definition info from url 'https://raw.githubusercontent.com/maysunfaisal/devfileexample/main/case4/nodeploy.yaml': failed to retrieve https://raw.githubusercontent.com/maysunfaisal/devfileexample/main/case4/nodeploy.yaml, 404: Not Found
Reason:                Error
Status:                False
Type:                  Created
```
N/A
Testing and documentation do not need to be complete in order for this PR to be …

Remove the error wrapping for reading K8s/OpenShift YAMLs

---

pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This issue fixes the bug that if the uri is not able to resolve from rawcontent, it will be ignored. Now it errors out with the message `error getting kubernetes resources definition information, unable to resolve the file uri: %v", uri`
Also added test for the function `getKubernetesDefinitionFromUri`, where the bug was found. 
Fixes https://github.com/devfile/api/issues/1039
>  **or**
> -  If …

error out if unable to resolve the path from raw content

---

pkg/devfile/generator/generators.go
pkg/devfile/generator/generators_test.go

The PR adds the ability to filter the containers included in the `generator.PodTemplateSpec()` when calling GetPodTemplateSpec. This is equivalent to filtering when calling `GetContainers()`
>  **or**

Add DevfileOptions to GetPodTemplateSpec

---

go.mod
go.sum
license_header.txt
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go

Pulls in latest devfile/api module, which contains the endpoint validation update. 
fixes https://github.com/devfile/api/issues/1049
>  **or**

pull in validation update

---

go.mod
pkg/devfile/imageNameSelector.go
pkg/devfile/imageNameSelector_test.go
pkg/devfile/parse.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

This PR introduces a new `ImageNamesAsSelector` field in the Devfile parser args. If this field is not `nil`, the parser will try to use image names from Image components as selectors in any matching Container or Kubernetes/OpenShift components.
In this case, the parser will return a Devfile object where all matching image names have been replaced with the arguments provided in the parser args.
Replacement is done only on relative image names and the logic to check whether there is a match is based on the discussion in https://github.com/devfile/api/issues/985#issuecomment-1404939472.
This is needed by `odo` (https://github.com/redhat-developer/odo/issues/6565).
Fixes https://github.com/devfile/api/issues/985
Fixes https://github.com/redhat-developer/odo/issues/6676
Testing and …

Allow using image names as selectors

---

README.md
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go

Gates the logic for downloading git resources. Clients od devfile/library may be running behind a proxy, so we cannot invoke git operations as they may fail
Fixes https://github.com/devfile/api/issues/1176
>  **or**

Gate downloading of git resources

---

.github/workflows/codecov.yml
.github/workflows/go.yml

This PR updates all deprecated github actions using NodeJS 12 in order to use NodeJS 16. The list of actions updated are:
- `actions/checkout@v2` > `actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3`
- `actions/setup-go@v2` > `actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0`
- `codecov/codecov-action@2.1.0` > `codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4`
Fixes https://github.com/devfile/api/issues/1225
>  - There is a separate tracking issue. Add the issue link …

Update github actions to use NodeJS 16

---

OWNERS
README.md

* Includes all team inside OWNERS file
* Updates the release section inside README.md with a list of steps to create a new release. It also mentions explicitly that releases are created on demand.
task of devtools week sep 2023
>  **or**

[devtools week] Update OWNERS file & update release section

---

.codecov.yaml
README.md
pkg/devfile/parse_test.go
pkg/devfile/parser/context/content.go
pkg/devfile/parser/context/content_test.go
pkg/devfile/parser/context/context.go
pkg/devfile/parser/context/context_test.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go
pkg/devfile/parser/reader.go
pkg/devfile/parser/reader_test.go
pkg/devfile/parser/util/interface.go
pkg/devfile/parser/util/mock.go
pkg/devfile/parser/util/utils.go
pkg/devfile/parser/util/utils_test.go
pkg/devfile/parser/utils.go
pkg/devfile/parser/utils_test.go
pkg/util/mock.go
pkg/util/util.go

- Implement Interface definition for DownloadInMemory and DownloadGitRepoResources
- Provide mock implementation DownloadInMemory
- Update all occurrences of DownloadInMemory invocation
- Update tests to include handling of mock invocation
- Update YAML Reader func ReadKubernetesYaml() to pass in Token and Devfile Utils Client to enable reading from private git repos
- Update function/API description to highlight new updates/changes
- Update README and documentation how to use Devfile Utils
Fixes https://github.com/devfile/api/issues/1221
Tests should pass

Implement Interface definition for DownloadInMemory

---

pkg/devfile/parser/util/mock.go
pkg/devfile/parser/util/utils_test.go
pkg/util/mock.go

- Adds the ability to use mock implementation without passing in mock data. Sometimes the client like HAS doesn't have the ability to pass in mock argument information always
- If no token is passed, dont mock output
tests should pass

Add ability to use mock without passing in arguments

---

CONTRIBUTING.md
README.md

This PR updates docs with release schedule as discussed during previous community call
devtools week item. 

update docs with release schedule

---

.github/workflows/scorecard.yml

Enables the openssf scorecard code scanning so that we can add the openssf scorecard to our repository. This is apart of the CNCF Cleaner tasks.
fixes https://github.com/devfile/api/issues/1369

add openssf scorecard workflow

---

pkg/devfile/parse.go
pkg/devfile/parser/context/apiVersion.go
pkg/devfile/parser/context/apiVersion_test.go
pkg/devfile/parser/context/content.go
pkg/devfile/parser/context/context_test.go
pkg/devfile/parser/context/schema.go
pkg/devfile/parser/errors/errors.go
pkg/devfile/parser/parse.go
pkg/devfile/parser/parse_test.go
pkg/devfile/parser/reader.go

- Introduces err codes for user errors in devfile, so this helps devfile/library consumers with prometheus metrics
- remove unnecessary error wrapping
Partially https://issues.redhat.com/browse/DEVHAS-580
tests should pass

Introduce err code for user error in devfile

---

pkg/devfile/parser/util/mock.go
pkg/devfile/parser/util/utils.go
pkg/devfile/parser/util/utils_test.go

This PR updates the `DownloadGitRepoResources` function to allow for different naming schemes for devfiles to be supported. Before the change only `devfile.yaml` was being recognized. This PR adds support for `devfile.yaml`, `devfile.yml`, `.devfile.yaml` and `.devfile.yml`.  In addition to this it allows for more naming schemes to be added in the future.
fixes https://github.com/devfile/api/issues/1362
Running `make test` should pass with the addition of the new tests for the devfile validation.

Add Functionality For Multiple Devfile Name Variations

---

SECURITY-INSIGHTS.yml

As suggested inside the `library_security` clo monitoring, a distribution-points section should be added inside the `SECURITY-INSIGHTS.yml`. Following examples for other repos the distribution points value can be the link to library's repo.
related to https://github.com/devfile/api/issues/1392

Add distribution-points to security-insights

---

pkg/devfile/parse_test.go
pkg/devfile/parser/data/helper.go
pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
pkg/devfile/parser/data/v2/2.2.1/devfileJsonSchema221.go
pkg/devfile/parser/data/v2/2.2.2/devfileJsonSchema222.go
pkg/devfile/parser/data/versions.go

A summary of changes made in this PR can be found below:
1. Added schema version 2.2.1 and 2.2.2 to the library, they are now recognized and parsable.
2. Updated 2.2.0 version to reference 2.2.0 release instead of 2.1.1-alpha as 2.1.1 is now added itself
3. Added new case to existing unit test to verify unsupported schemas are being picked up and tested
fixes https://github.com/devfile/api/issues/1454
Unit tests ran with `make test` should pass. Additionally when you try and parse a devfile on schema 2.2.1 or 2.2.2 now it should function and not spit an error message.

add support for 2.2.1 and 2.2.2 schema versions

---

.github/workflows/go.yml

This PR should allow the `security-events` steps of our go workflow to have write permissions, this would allow the SARIF file step to properly write. I am under the belief that the changes made in [this PR](https://github.com/devfile/library/pull/203) that added `permissions: read-all` added the default permissions for the whole workflow to only read, which was blocking the SARIF write.
fixes https://github.com/devfile/api/issues/1495
The SARIF test was failing on my fork before the change and is now passing with the change

patch: add write permission for sarif file

---

pkg/devfile/parser/parse_test.go

Adds a bypass error case to expect `Get "http://http//invalid.com/devfiles/notexist/": dial tcp: lookup http on 127.0.0.53:53: server misbehaving` for invalid registry urls in Ubuntu Server instances, which are the instances known to give this error for invalid urls when using `Go 1.21`.
fixes devfile/api#1588
Use `Go 1.21.10` under an [Ubuntu Server 22.04 LTS](https://releases.ubuntu.com/22.04/ubuntu-22.04.4-live-server-amd64.iso) instances and run:
```
make test
```

Add ubuntu server bypass error case for invalid registry urls

---

tests/v2/devfiles/samples/Test_Parent_RegistryURL.yaml

The `Test_Parent_RegistryURL.yaml` consumes the latest parent version of `nodejs`. As a result any breaking changes will impact the library's tests. This PR simply fixes the version to `2.2.1` (current latest) so the test related to this file remain unimpacted by any changes of the `devfile/registry)
N/A

Fix parent version on test devfile

---

CONTRIBUTING.md
README.md

Updates references to the Go runtime in the documentation to refer to Go 1.21, added in #212.

Update references to Go 1.21 in docs

---

pkg/devfile/parse_test.go
pkg/devfile/parser/data/v2/2.3.0/devfileJsonSchema230.go
pkg/devfile/parser/data/versions.go
scripts/updateApi.sh

A summary of changes made in this PR can be found below:
1. Updated `updateApi.sh` include recent API versions
2. Added schema version 2.3.0 to the library, now recognized and parsable.
fixes devfile/api#1593

Add support for 2.3.0 schema version

---

.github/PULL_REQUEST_TEMPLATE.md
OWNERS

- Updates the PR template as part of devtools week
- Updates OWNERS file 
N/A

Update PR template and OWNERS

---

pkg/devfile/generator/generators_test.go
pkg/devfile/generator/utils.go

Updating  ENV list for all special/reserved ENVs
fixes: https://github.com/devfile/api/issues/1601

add projectsrc to env

---

go.mod
go.sum
pkg/devfile/imageNameSelector.go

_Summarize the changes you made as part of this pull request._
- update distribution/reference to v0.6.0
- update "github.com/distribution/distribution/v3/reference" imports to "github.com/distribution/reference"
_Link the GitHub/GitLab/JIRA issues that are related to this PR._
https://github.com/openshift/console/pull/14841
no code changes. I am just updating an import as [distribution/v3/reference](https://pkg.go.dev/github.com/distribution/distribution/v3/reference) does not appear to be a valid go import. this is causing some error in openshift console:
```
go: finding module for package github.com/distribution/distribution/v3/reference
go: github.com/openshift/console/pkg/devfile imports
github.com/devfile/library/v2/pkg/devfile imports …
```

update distribution/reference import

---

.github/workflows/go.yml
.github/workflows/scorecard.yml
CONTRIBUTING.md
README.md
go.mod
pkg/devfile/generator/generators_test.go
pkg/devfile/parser/data/helper.go
pkg/devfile/parser/utils.go
pkg/devfile/parser/utils_test.go
tests/v2/utils/library/test_utils.go

Updating go version from 1.21 to 1.24
Needed some linting changes (error output format) to keep up with 1.24 rules. 
https://github.com/devfile/api/issues/1699
_Testing and documentation do not need to be complete in order for this PR to be approved. However, tracking issues must be opened for missing testing/documentation._
New testing and documentation issues can be opened under [`devfile/api/issues`](https://github.com/devfile/api/issues).
You can check the respective criteria below if either of the following is true:
- There is a separate tracking issue opened and that issue is linked in this PR.
- Testing/documentation updates are contained within this PR.
If criteria is left unchecked please provide an explanation why.
- [o] Unit/Functional tests
- [o] [QE Integration …

Updating go version 1.24, fixing linting errors
