devfile/library

- README.md
Initial readme that describes what this project is about and what would consume it.
> Add readme to the project

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/PULL_REQUEST_TEMPLATE.md
Add PR and issues templates.
It's pretty the same templates https://github.com/devfile/kubernetes-api has.
N/A
No testing it needed. It's just GitHub repo settings.
> Add PR and issues templates

- .gitignore
This PR fixes .gitignore so that it won't ignore any folder with the name "parser"".   
* Create a folder "parser" and add some files to the folder.  
* 'git status' should display those files.
> Fix .gitignore so that it won't ignore parser folders

- README.md
Updates the Readme with links to track issues
N/A
N/A
> Update Readme with links

- pkg/devfile/parser/context/context.go
This PR adds the missing function to setAbdPath() for devfile ctx
> add setAbsPath()

- go.mod
- go.sum
- pkg/devfile/parser/configurables.go
pull in latest devfile/api change which update the protocol type in endpoint
> pull in latest devfile/api change

- OWNERS
- pkg/devfile/OWNERS
Updates the owners file. Added team members from other repo as approvers in addition to this repo maintainers
> Update owners file

- go.mod
- go.sum
- pkg/devfile/parser/configurables_test.go
- pkg/devfile/parser/data/v2/2.1.0/devfileJsonSchema210.go
- pkg/devfile/parser/data/v2/events_test.go
- pkg/devfile/parser/parse_test.go
- updateApi.sh
this pr updates to use latest devfile api struct and schema
updated some tests since the `WorkspaceEvents` has been updated to `DevWorkspaceEvents`
also update the script to pull from `main` branch instead of `master`
> update to latest devfile/api

- go.mod
- go.sum
- pkg/devfile/validate/validate.go
This PR gets the latest commit from api repo which contains a bug fix for command validation. 
This PR updates library validator to use multierrors as well, this guarantees the error received by tools will be well constructed. 
https://github.com/devfile/api/issues/577
>  **or**
> use multierror in library

- devfile.yaml
- go.mod
- go.sum
- pkg/devfile/parser/context/apiVersion.go
- pkg/devfile/parser/context/apiVersion_test.go
- pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
- pkg/devfile/parser/data/versions.go
support concrete schema version, 
get latest devfile api and schema
Fixes https://github.com/devfile/api/issues/625
>  **or**
run unit tests
or parse devfile with a concrete schema version
> support concrete schema version

- pkg/devfile/parser/data/v2/common/component_helper.go
- pkg/devfile/parser/data/v2/common/component_helper_test.go
- pkg/devfile/parser/devfileobj.go
This PR update the library for the new image component type added for outer loop support. No changes needed for the new group kind `deploy`
Also updates the unit test for it's particular helper function to test image component type. 
The changes need to be made in functional tests in api and library can by tracked via https://github.com/devfile/api/issues/627
https://github.com/devfile/api/issues/626
>  **or**
>  - test/doc updates are made as part …
> update library for image component type

- pkg/util/util.go
Removes the zip extension check against the zip source URL.
devfile/api#796
>  **or**
> Remove zip ext check for zipUrl within GetAndExtractZip

- pkg/util/util_test.go
Signed-off-by: Michael Hoang <mhoang@redhat.com>
Noticed that there were devfile library util unit tests in the odo repo that could be moved here.
Tests copied from https://github.com/redhat-developer/odo/blob/main/pkg/util/util_test.go
>  **or**
> adding util tests from odo

- devfile.yaml
this PR revert back devfile changes
>  **or**
> revert back devfile change

- README.md
- pkg/devfile/parser/parse.go
- pkg/util/util.go
Backports the changes to a dependency release supported by console 4.10 and 4.9. Fix was verified in 4.12 by the console team
https://github.com/devfile/api/issues/926
>  **or**
> backport proxy and custom timeout support to console v4.10

- go.mod
- go.sum
- pkg/devfile/parser/parse_test.go
> update registry-library version

- license_header.txt
Updates the copyrights line to `Copyright Red Hat`.
fixes https://github.com/devfile/api/issues/1244
>  **or**
> [Devtools week] Update license headers

- .vscode/launch.json
add debugger launch file
>  **or**
> add debugger launch file

- go.mod
- go.sum
- pkg/devfile/parser/data/v2/2.2.0/devfileJsonSchema220.go
Pull in devfile/api 2.2.1 release
fixes https://github.com/devfile/api/issues/1285
>  **or**
> Pull in devfile/api 2.2.1 release

- .clomonitor.yml
- README.md
These changes fix all but one issue as part of the tasks required for the Cleaner Badge. The last item on the list will be brought up in discussion when the team is back after recharge.
fixes https://github.com/devfile/api/issues/1369
> CNCF Cleaner Tasks for CLO Monitor

- README.md
This PR follows up on the GitHub action added as part of https://github.com/devfile/library/pull/195. This adds the scorecard badge that reflects the addition and results of the workflow added.
fixes https://github.com/devfile/api/issues/1369
> add scorecard badge to readme

- README.md
This PR updates the readme to properly outline that the parser supports `v2.3.0` of the devfile schema. This is in preparation for release `v2.3.0` of devfile/library
N/A
> Prepare for v2.3.0 release
